### ISSUE TITLE
Support for fragments in persisted queries (babel-plugin-extract-gql)

### ISSUE THREAD

**Issue by matepaiva** [nearform/graphql-hooks#661] opened 2021-07-26 12:04 UTC
### Description

The query below should work, persisting the query with the fragment to the local disk. But it's generating the query without the fragments.

```
const query = persist`
  query pricingQuery {
    pmpro {
      levels {
        id
        name
        ...MembershipLevelPreview_level
      }
    }
  }
  ${fragmentMembershipLevelPreview_level}
`;
```

### Suggested implementation

I don't know how to implement it, as I have never done a babel plugin. I am willing to contribute, but I need some guidance.

**Comment by clemarc** [comment] 2021-07-29 15:06
I had a look and the issue isn't really with the fragment but with the interpolation, the plugin is explicitly ignoring dynamic strings.

https://github.com/nearform/graphql-hooks/blob/00e76b9c12537958cc55e35f7ce44d518ceaa19b/packages/babel-plugin-extract-gql/src/index.js#L35

If you put the fragment inline then it works.
```js
const query = persist`
  query pricingQuery {
    pmpro {
      levels {
        id
        name
        ...MembershipLevelPreview_level
      }
    }
  }
  fragment MembershipLevelPreview_level on levels {
    somField
  }
`;
```

You are losing the reusability of fragment by doing so but I'm not sure we can handle interpolation as the value can be dynamic at runtime.

**Comment by matepaiva** [comment] 2021-07-29 17:08
I ended up writing my own plugin based on this one and injecting the fragments at build time. My approach was:

1. I wrapped my fragments in a template string like
 ```graphql
 # could be other name, but persist works fine with the current plugin
 persist`
   fragment blablabla on Blablabla {
      name
   } 
 `
 ```
2. So the plugin also saves the value of the fragment to the json file.
3. I created a script to send the query hash dictionary to the server. In that script, I inject the used fragments using my stored fragments.
4. That's all, it works fine.

The only small issue is that the hash is generated based on the query without the injected fragments, so if a fragment content is updated the hash will not change, and that is error prone.

I understand that this approach is opinionated because it assumes that the query fragments will be injected. Other possibility would be handling the interpolation and injecting it's content at compilation, but I have no idea how to do that, hehe.

**Comment by clemarc** [comment] 2021-07-30 08:48
@matepaiva That sounds like a good workaround until there's a better way to declare and handle fragments.

Closing the issue.

**Closed by clemarc** 2021-07-30 08:48 UTC
Labels: feature
