### ISSUE TITLE
Argument of type 'Context<GraphQLClient | null>' is not assignable to parameter of type '

### ISSUE THREAD

**Issue by Jeric-Disney** [nearform/graphql-hooks#893] opened 2022-08-13 13:10 UTC
### Package

`graphql-hooks`

### Environment

- `graphql-hooks` version: 5.11.4
- `react` version: 18.2
- Browser: chrome

### Description

using useContext to get the client

### How to reproduce

```jsx
import {ClientContext} from 'graphql-hooks'
...
const client = React.useContext(ClientContext)
```

**Comment by simoneb** [comment] 2022-08-19 16:13
Can you clarify what issue you're having? The types are defined [here](https://github.com/nearform/graphql-hooks/blob/master/packages/graphql-hooks/src/ClientContext.ts) and they look correct to me.

**Comment by helderdb** [comment] 2022-09-30 14:07
I think I'm having the same issue. It started on version 5.1.0

The problem is that instead of wrapping the app with <ClientContext.Provider>...</ClientContext.Provider>, we're using 
```
React.createElement(ClientContext.Provider,
    {
      value: client,
    },
    app);
```

This breaks the hooks plugin, and the context isn't defined anymore.

**Comment by simoneb** [comment] 2022-09-30 14:20
@helderdb thanks for clarifying. Would you be interested in sending a PR to address this?

**Comment by helderdb** [comment] 2022-10-06 10:13
@simoneb @Jeric-Disney Found the issue! We were instantiating the hooks plugin through a custom module. Since we were developing and referencing the module through a file resolver in our projects package.json, the module also had it's own node_modules folder. It then referenced that specific version of graphql-hooks in the module, while our project was using graphql-hooks from a level above in the node_modules folder.

So we were actually using separate instances, and that's why the ClientContext didn't work.

**Comment by simoneb** [comment] 2022-10-06 10:25
Thanks for the follow-up @helderdb . Feel free to close this issue then

**Closed** 2022-10-11 15:55 UTC
Labels: bug
